allowBuilds:
  core-js: false
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
  workerd: false
minimumReleaseAgeExclude:
  - posthog-js@1.415.6
  - miniflare@5.20260811.0-alpha
  - wrangler@4.122.0
